runtime: java17
env: flex

handlers:
- url: /.*
  script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
 

resources:
  cpu: 1
  memory_gb: 2.3
  disk_size_gb: 10